name: "{{projectName}}"
description: A project created by Very Good CLI and hello_riverpod
version: 0.0.1+1

# Prevent accidental publishing to pub.dev.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^13.0.1
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  mocktail: ^1.0.2
  riverpod_annotation: ^2.0.0
  shared_preferences: ^2.2.3
  slang: ^3.14.0
  slang_flutter: ^3.14.0
  test: ^1.22.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  riverpod_generator: ^2.0.0
  slang_build_runner: ^3.14.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files
  assets:
    - assets/
