name: "{{projectName}}"
description: A beautiful project created by hello_riverpod
version: 0.1.0+1

# Prevent accidental publishing to pub.dev.
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  bot_toast: ^4.1.3 # necessary for Snowflake
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  mocktail: ^1.0.4
  riverpod_annotation: ^2.6.0
  shared_preferences: ^2.3.2
  slang: ^4.0.0
  slang_flutter: ^4.0.0
  snowflake_flutter_theme:
    git:
      url: https://github.com/icodeyou/snowflake_flutter_theme
      ref: "0.0.10"
  test: ^1.25.7

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  slang_build_runner: ^4.0.0
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
