name: "{{projectName}}"
description: A project created by Very Good CLI and hello_riverpod
version: 1.0.0+1

# Prevent accidental publishing to pub.dev.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.2.2
  mocktail: ^0.3.0
  riverpod_annotation: ^2.0.0
  test: ^1.22.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  riverpod_generator: ^2.0.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files
  assets:
    - assets/
