name: "{{projectName}}"
description: A project created by Very Good CLI and hello_riverpod
version: 0.1.0+1

# Prevent accidental publishing to pub.dev.
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  mocktail: ^1.0.4
  riverpod_annotation: ^2.6.0
  shared_preferences: ^2.3.2
  slang: ^3.32.0
  slang_flutter: ^3.32.0
  test: ^1.22.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  slang_build_runner: ^3.32.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files
  assets:
    - assets/images/
